<a href="https://colab.research.google.com/github/Stitchkoh/Story/blob/master/ArrayProjectPratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

array_a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

array_b= array_a.reshape(1,16)

print(array_b)



[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [11]:
import numpy as np

array_a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

array_b= array_a.reshape(2,8)

print(array_b)

array_c = array_a.T

print(array_c.T.T.T.T.T.T)







[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [16]:
print(array_c[0,1], array_c[2])

print(array_c[-1,3],array_c[1,1])
print(array_c[1,-2])




5 [ 3  7 11 15]
16 6
10


In [28]:
import numpy as np

array_a = np.array([[1,2,3],[4,5,6]],dtype=float)
print(array_a.size)
print(array_a.shape)
print(array_a)
array_b = np.zeros((3,4))
print(array_b)
array_c=np.ones((4,4))
print(array_c)
array_d = np.full((4,4),100)
print(array_d)
array_e = np.random.random((10,4))
print(array_e)








6
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[0.26603699 0.42037258 0.28415996 0.21268924]
 [0.61012321 0.70956817 0.82386419 0.6805547 ]
 [0.68601164 0.97193616 0.30072551 0.12248962]
 [0.89411256 0.93036777 0.78925845 0.35132785]
 [0.97411808 0.1810701  0.30747573 0.97891649]
 [0.61556731 0.3466649  0.19463627 0.6702787 ]
 [0.7636785  0.31680861 0.18658036 0.8065061 ]
 [0.70885209 0.05309241 0.83092841 0.10169826]
 [0.0141828  0.56778612 0.24588297 0.21632866]
 [0.64891195 0.38404093 0.66711008 0.3768369 ]]


In [29]:
import numpy as np


array_a = np.array([32766, 32767, 32769])
print(array_a)


[32766 32767 32769]
